// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBePegmo_ehjBeXQY8pZYKiIbDWg4KMX0I',
    appId: '1:880851798790:web:0dd4ef408b62a270eaac87',
    messagingSenderId: '880851798790',
    projectId: 'flutterlisting-9944a',
    authDomain: 'flutterlisting-9944a.firebaseapp.com',
    storageBucket: 'flutterlisting-9944a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMIgq1xl5kMaFDG1UbwjjpuOzAuqEiv0',
    appId: '1:880851798790:android:e278eb537a7eceb2eaac87',
    messagingSenderId: '880851798790',
    projectId: 'flutterlisting-9944a',
    storageBucket: 'flutterlisting-9944a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGjHmxmT60VnSrHqglWkgqO24i9l_2lw',
    appId: '1:880851798790:ios:2d1fe5b771d9c2f9eaac87',
    messagingSenderId: '880851798790',
    projectId: 'flutterlisting-9944a',
    storageBucket: 'flutterlisting-9944a.appspot.com',
    iosBundleId: 'com.example.flutterListingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGjHmxmT60VnSrHqglWkgqO24i9l_2lw',
    appId: '1:880851798790:ios:2d1fe5b771d9c2f9eaac87',
    messagingSenderId: '880851798790',
    projectId: 'flutterlisting-9944a',
    storageBucket: 'flutterlisting-9944a.appspot.com',
    iosBundleId: 'com.example.flutterListingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBePegmo_ehjBeXQY8pZYKiIbDWg4KMX0I',
    appId: '1:880851798790:web:9e59e86e5eda7488eaac87',
    messagingSenderId: '880851798790',
    projectId: 'flutterlisting-9944a',
    authDomain: 'flutterlisting-9944a.firebaseapp.com',
    storageBucket: 'flutterlisting-9944a.appspot.com',
  );
}
